# Generated by Django 2.1 on 2018-08-20 10:07

from django.db import migrations, models
import django.db.models.deletion
import order_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=None, max_length=32, null=True, verbose_name='Own Order ID')),
                ('status', models.CharField(choices=[('NEW', 'new'), ('INVALID', 'invalud'), ('CREATED', 'created'), ('FULFILLMENT', 'fulfillment'), ('FULFILLMENT_NOTIFIED', 'fulfillment(n)'), ('SENT', 'sent'), ('SENT_NOTIFIED', 'sent(n)')], default=order_app.models.OrderStatus('new'), max_length=32, verbose_name='Own Status')),
                ('channel', models.CharField(default=None, max_length=32, null=True, verbose_name='Channel')),
                ('channel_order_id', models.CharField(default=None, max_length=64, null=True, verbose_name="Channel's Order ID")),
                ('channel_status', models.CharField(default=None, max_length=32, null=True, verbose_name='Channel')),
                ('address', models.CharField(max_length=1024, verbose_name='Address')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'verbose_name': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, verbose_name='Stock Keeping Unit')),
                ('title', models.CharField(max_length=512, verbose_name='Title')),
                ('channel_item_id', models.CharField(default=None, max_length=64, null=True, verbose_name="Channel's Item ID")),
                ('channel_order_item_id', models.CharField(default=None, max_length=64, null=True, verbose_name="Channel's Order-item ID")),
                ('channel_status', models.CharField(max_length=64, verbose_name="Channel's Order-item Status")),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price of item')),
                ('amount', models.IntegerField(verbose_name='Number of items')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_app.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name_plural': 'Order Items',
                'verbose_name': 'Order Item',
            },
        ),
        migrations.CreateModel(
            name='Picker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name="Picker's name")),
                ('items_collected', models.IntegerField(default=0, verbose_name='Number of items collected')),
            ],
            options={
                'verbose_name_plural': 'Pickers',
                'verbose_name': 'Picker',
            },
        ),
    ]
